# Generated by Django 4.2.3 on 2023-08-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_auction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'объявлеине', 'verbose_name_plural': 'объявления'},
        ),
    ]
